name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha Primeira ação"
        run: echo "Hello World!!!"
      - name: "Segunda ação"
        run: |
          echo "Você criou o seu primeiro workflow !!!"
          echo "Parabéns"
      - name: "Script Python"
        run: |
          variavel = "Hello world !!!"
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalação do ambiente NodJS"      
    runs-on: ubuntu-latest
    needs: [primeiro-job]
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
      - name: "Definição da versão v20.18.0 do NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: 'v20.18.0'
      - name: "Verificação da versão do NodeJS depois de instalar"
        run: node --version
